version: '3.3'

services:
  rds:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: test-db