version: '3.3'
services:
    dp-areas-api:
        build:
            context: ../../../dp-areas-api
            dockerfile: Dockerfile.local
        command:
            - go
            - test
            - -cover
            - -race
            - -coverpkg=github.com/ONSdigital/dp-areas-api/...
            - -component
        volumes:
            - ../../:/dp-areas-api
        ports:
            - 27100:27100
        environment:
            BIND_ADDR:              ":27100"
            SERVICE_AUTH_TOKEN:     "testToken"
            USEPOSTGRESLOCAL:       "true"
            DPPOSTGRESUSERNAME:     "user"
            DPPOSTGRESPASSWORD:     "password"
            DPPOSTGRESPORT:         "postgres://rds:5432"
            USEPOSTGRESDB:          "db"
