linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - unused
    - depguard
    - dogsled
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - govet
    - ineffassign
    - nakedret
    - unconvert
    - whitespace
    - gocognit
    - prealloc
