// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	dpareasapirds "github.com/ONSdigital/dp-areas-api/rds"
	servicerds "github.com/aws/aws-sdk-go/service/rds"
	"sync"
)

// Ensure, that ClientMock does implement dpareasapirds.Client.
// If this is not the case, regenerate this file with moq.
var _ dpareasapirds.Client = &ClientMock{}

// ClientMock is a mock implementation of dpareasapirds.Client.
//
// 	func TestSomethingThatUsesClient(t *testing.T) {
//
// 		// make and configure a mocked dpareasapirds.Client
// 		mockedClient := &ClientMock{
// 			DescribeDBInstancesFunc: func(input *servicerds.DescribeDBInstancesInput) (*servicerds.DescribeDBInstancesOutput, error) {
// 				panic("mock out the DescribeDBInstances method")
// 			},
// 		}
//
// 		// use mockedClient in code that requires dpareasapirds.Client
// 		// and then make assertions.
//
// 	}
type ClientMock struct {
	// DescribeDBInstancesFunc mocks the DescribeDBInstances method.
	DescribeDBInstancesFunc func(input *servicerds.DescribeDBInstancesInput) (*servicerds.DescribeDBInstancesOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// DescribeDBInstances holds details about calls to the DescribeDBInstances method.
		DescribeDBInstances []struct {
			// Input is the input argument value.
			Input *servicerds.DescribeDBInstancesInput
		}
	}
	lockDescribeDBInstances sync.RWMutex
}

// DescribeDBInstances calls DescribeDBInstancesFunc.
func (mock *ClientMock) DescribeDBInstances(input *servicerds.DescribeDBInstancesInput) (*servicerds.DescribeDBInstancesOutput, error) {
	if mock.DescribeDBInstancesFunc == nil {
		panic("ClientMock.DescribeDBInstancesFunc: method is nil but Client.DescribeDBInstances was just called")
	}
	callInfo := struct {
		Input *servicerds.DescribeDBInstancesInput
	}{
		Input: input,
	}
	mock.lockDescribeDBInstances.Lock()
	mock.calls.DescribeDBInstances = append(mock.calls.DescribeDBInstances, callInfo)
	mock.lockDescribeDBInstances.Unlock()
	return mock.DescribeDBInstancesFunc(input)
}

// DescribeDBInstancesCalls gets all the calls that were made to DescribeDBInstances.
// Check the length with:
//     len(mockedClient.DescribeDBInstancesCalls())
func (mock *ClientMock) DescribeDBInstancesCalls() []struct {
	Input *servicerds.DescribeDBInstancesInput
} {
	var calls []struct {
		Input *servicerds.DescribeDBInstancesInput
	}
	mock.lockDescribeDBInstances.RLock()
	calls = mock.calls.DescribeDBInstances
	mock.lockDescribeDBInstances.RUnlock()
	return calls
}
