// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storetest

import (
	"sync"

	"github.com/ONSdigital/dp-topic-api/models"
	"github.com/ONSdigital/dp-topic-api/store"
)

var (
	lockStorerMockGetTopic sync.RWMutex
)

// Ensure, that StorerMock does implement store.Storer.
// If this is not the case, regenerate this file with moq.
var _ store.Storer = &StorerMock{}

// StorerMock is a mock implementation of store.Storer.
//
//     func TestSomethingThatUsesStorer(t *testing.T) {
//
//         // make and configure a mocked store.Storer
//         mockedStorer := &StorerMock{
//             GetTopicFunc: func(ID string) (*models.DatasetUpdate, error) {
// 	               panic("mock out the GetTopic method")
//             },
//         }
//
//         // use mockedStorer in code that requires store.Storer
//         // and then make assertions.
//
//     }

type StorerMock struct {
	// GetTopicFunc mocks the GetTopic method.
	GetTopicFunc func(ID string) (*models.TopicUpdate, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetTopic holds details about calls to the GetTopic method.
		GetTopic []struct {
			// ID is the ID argument value.
			ID string
		}
	}
}

// GetTopic calls GetTopicFunc.
func (mock *StorerMock) GetTopic(ID string) (*models.TopicUpdate, error) {
	if mock.GetTopicFunc == nil {
		panic("StorerMock.GetTopicFunc: method is nil but Storer.GetTopic was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: ID,
	}
	lockStorerMockGetTopic.Lock()
	mock.calls.GetTopic = append(mock.calls.GetTopic, callInfo)
	lockStorerMockGetTopic.Unlock()
	return mock.GetTopicFunc(ID)
}

// GetTopicCalls gets all the calls that were made to GetTopic.
// Check the length with:
//     len(mockedStorer.GetTopicCalls())
func (mock *StorerMock) GetTopicCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockStorerMockGetTopic.RLock()
	calls = mock.calls.GetTopic
	lockStorerMockGetTopic.RUnlock()
	return calls
}
