// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storetest

import (
	"context"
	"sync"

	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"github.com/ONSdigital/dp-topic-api/models"
)

var (
	lockMongoDBMockChecker  sync.RWMutex
	lockMongoDBMockClose    sync.RWMutex
	lockMongoDBMockGetTopic sync.RWMutex
)

// MongoDBMock is a mock implementation of store.MongoDB.
//
//     func TestSomethingThatUsesMongoServer(t *testing.T) {
//
//         // make and configure a mocked store.MongoDB
//         mockedMongoServer := &MongoDBMock{
//             CheckerFunc: func(ctx context.Context, state *healthcheck.CheckState) error {
// 	               panic("mock out the Checker method")
//             },
//             CloseFunc: func(ctx context.Context) error {
// 	               panic("mock out the Close method")
//             },
//             GetTopicFunc: func(id string) (*models.TopicResponse, error) {
// 	               panic("mock out the GetTopic method")
//             },
//         }
//
//         // use mockedMongoServer in code that requires store.MongoDB
//         // and then make assertions.
//
//     }
type MongoDBMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(ctx context.Context, state *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(ctx context.Context) error

	// GetTopicFunc mocks the GetTopic method.
	GetTopicFunc func(id string) (*models.TopicResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetTopic holds details about calls to the GetTopic method.
		GetTopic []struct {
			// ID is the id argument value.
			ID string
		}
	}
}

// Checker calls CheckerFunc.
func (mock *MongoDBMock) Checker(ctx context.Context, state *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("MongoDBMock.CheckerFunc: method is nil but MongoServer.Checker was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}{
		Ctx:   ctx,
		State: state,
	}
	lockMongoDBMockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	lockMongoDBMockChecker.Unlock()
	return mock.CheckerFunc(ctx, state)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//     len(mockedMongoServer.CheckerCalls())
func (mock *MongoDBMock) CheckerCalls() []struct {
	Ctx   context.Context
	State *healthcheck.CheckState
} {
	var calls []struct {
		Ctx   context.Context
		State *healthcheck.CheckState
	}
	lockMongoDBMockChecker.RLock()
	calls = mock.calls.Checker
	lockMongoDBMockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *MongoDBMock) Close(ctx context.Context) error {
	if mock.CloseFunc == nil {
		panic("MongoDBMock.CloseFunc: method is nil but MongoServer.Close was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockMongoDBMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockMongoDBMockClose.Unlock()
	return mock.CloseFunc(ctx)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedMongoServer.CloseCalls())
func (mock *MongoDBMock) CloseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockMongoDBMockClose.RLock()
	calls = mock.calls.Close
	lockMongoDBMockClose.RUnlock()
	return calls
}

// GetTopic calls GetTopicFunc.
func (mock *MongoDBMock) GetTopic(id string) (*models.TopicResponse, error) {
	if mock.GetTopicFunc == nil {
		panic("MongoDBMock.GetTopicFunc: method is nil but MongoServer.GetTopic was just called")
	}
	callInfo := struct {
		ID string
	}{
		ID: id,
	}
	lockMongoDBMockGetTopic.Lock()
	mock.calls.GetTopic = append(mock.calls.GetTopic, callInfo)
	lockMongoDBMockGetTopic.Unlock()
	return mock.GetTopicFunc(id)
}

// GetTopicCalls gets all the calls that were made to GetTopic.
// Check the length with:
//     len(mockedMongoServer.GetTopicCalls())
func (mock *MongoDBMock) GetTopicCalls() []struct {
	ID string
} {
	var calls []struct {
		ID string
	}
	lockMongoDBMockGetTopic.RLock()
	calls = mock.calls.GetTopic
	lockMongoDBMockGetTopic.RUnlock()
	return calls
}
